name: CI

on:
    push:
        branches: [ master ]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
                
            - name: Setup Android SDK
              uses: android-actions/setup-android@v2
          
            - name: Build SampleApplication
              run: ./gradlew assembleDebug testDebugUnitTest
              
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                fail_ci_if_error: true
                token: d1c2da7f-8567-44e2-b41d-50700a8b3a2d
